dataset:
  name: cifar10   # MNIST not supported, this is a placeholder
  link: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  format: pickle

model:
  script: configs/model/config_model_resnet20.py
  framework: pytorch
  params: {}

pipeline:
  pre_training:
    noop:
      name: pre_noop
      container:
        image: docker://ghcr.io/landseer-project/pre_noop:v1
        command: python main.py

  during_training:
    noop:
      name: in_noop
      container:
        image: docker://ghcr.io/landseer-project/in_noop:v5
        command: python main.py

  post_training:
    tools:
      - name: dawn
        container:
          image: docker://ghcr.io/landseer-project/post_noop:v1
          command: python main.py
        params:
          scores_dir: /scratch/gilbreth/schamara/DAWN/data/scores
          ground_truth_pattern: "*ground_truth*.pkl"
          watermark_pattern: "*watermark*.pkl"
    noop:
      name: post_noop
      container:
        image: docker://ghcr.io/landseer-project/post_noop:v1
        command: python main.py

  deployment:
    noop:
      name: deploy_noop
      container:
        image: docker://ghcr.io/landseer-project/deploy_noop:v1
        command: python main.py
